Controllers/ArticleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AppStock.Data;
using AppStock.Models;
using AppStock.Infrastructure.Services.Article;
using AppStock.Infrastructure.Services.Stock;
using System.Runtime.Serialization;

namespace AppStock.Controllers
{
    public class ArticleController : Controller
    {
        private readonly IArticleService _service;
        private readonly IStockService _service_stock;

        private readonly ApplicationDbContext _context;

        public ArticleController(IArticleService service, IStockService service_stock, ApplicationDbContext context)
        {
            _context = context;
            _service = service;
            _service_stock = service_stock;
        }

        // GET: Article
        public async Task<IActionResult> Index()
        {
            /*
                A FAIRE
                Pour filtrer les entites disponibles a l'affichage, il faudra determiner la nature de l'utilisateur
                    CLIENT  ->  tel quel (càd. avec les QueryFilters d'activés)
                    ADMIN   -> .IgnoreQueryFilters()
            */
            ViewData["Service"] = _service;
            return View(await _service.GetAll());
        }

        // GET: Article/Details/5
        public async Task<IActionResult> Details(int id)
        {
            var article = await _service.GetOneById(id);
            if (article == null)
            {
                return NotFound();
            }

            return View(article);
        }

        // GET: Article/Create
        public IActionResult Create()
        {
            /**
                A FAIRE :: preparer et utiliser les services manquants
            **/
            ViewData["FournisseurID"] = new SelectList(_context.FournisseurEntities, "Id", "Raison");
            ViewData["ArticleFamilleID"] = new SelectList(_context.ArticleFamilleEntities, "Id", "Code");
            ViewData["NomTypeTVAID"] = new SelectList(_context.NomTypeTVAEntities, "Id", "Code");
            return View();
        }

        // POST: Article/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Code,Libelle,PrixUnitaire,FournisseurId,ArticleFamilleId,NomTypeTVAId,Threshold")] ArticleEntity article)
        {
            if (ModelState.IsValid)
            {
                var item = await _service.Add(article);
                // init STOCK par defaut(quantite==threshold)
                await _service_stock.InitStockForArticle(article);
                return RedirectToAction(nameof(Index));
            }

            /**
                A FAIRE :: preparer et utiliser les services manquants
            **/
            ViewData["FournisseurID"] = new SelectList(_context.FournisseurEntities, "Id", "Raison", article.FournisseurId);
            ViewData["ArticleFamilleID"] = new SelectList(_context.ArticleFamilleEntities, "Id", "Code", article.ArticleFamilleId);
            ViewData["NomTypeTVAID"] = new SelectList(_context.NomTypeTVAEntities, "Id", "Code", article.NomTypeTVAId);
            return View(article);
        }

        // GET: Article/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            var article = await _service.GetOneById(id);
            if (article == null)
            {
                return NotFound();
            }

            /**
                A FAIRE :: preparer et utiliser les services manquants
            **/
            ViewData["FournisseurID"] = new SelectList(_context.FournisseurEntities, "Id", "Raison", article.FournisseurId);
            ViewData["ArticleFamilleID"] = new SelectList(_context.ArticleFamilleEntities, "Id", "Code", article.ArticleFamilleId);
            ViewData["NomTypeTVAID"] = new SelectList(_context.NomTypeTVAEntities, "Id", "Code", article.NomTypeTVAId);
            return View(article);
        }

        // POST: Article/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Code,Libelle,PrixUnitaire,FournisseurId,ArticleFamilleId,NomTypeTVAId,Threshold")] ArticleEntity article)
        {
            if (id != article.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _service.Update(article);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ArticleExists(article.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            
            /**
                A FAIRE :: preparer et utiliser les services manquants
            **/
            ViewData["FournisseurID"] = new SelectList(_context.FournisseurEntities, "Id", "Raison", article.FournisseurId);
            ViewData["ArticleFamilleID"] = new SelectList(_context.ArticleFamilleEntities, "Id", "Code", article.ArticleFamilleId);
            ViewData["NomTypeTVAID"] = new SelectList(_context.NomTypeTVAEntities, "Id", "Code", article.NomTypeTVAId);
            return View(article);
        }

        // GET: Article/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            var article = await _service.GetOneById(id);
            if (article == null)
            {
                return NotFound();
            }

            return View(article);
        }

        // POST: Article/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _service.DeleteById(id);
            return RedirectToAction(nameof(Index));
        }

        private bool ArticleExists(int id)
        {
            return _service.Exist(id);
        }
    }
}

Controllers/StockController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AppStock.Data;
using AppStock.Models;
using AppStock.Infrastructure.Services.Article;
using AppStock.Infrastructure.Services.Stock;

namespace AppStock.Controllers
{
    public class StockController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IStockService _service;
        private readonly IArticleService _serviceArticle;

        public StockController(ApplicationDbContext context, IStockService service, IArticleService service_article)
        {
            _context = context;
            _service = service;
            _serviceArticle = service_article;
        }

        // GET: Stock
        public async Task<IActionResult> Index()
        {
            return View(await _service.GetAll());
        }

        // GET: Stock/Details/5
        public async Task<IActionResult> Details(int id)
        {

            var stock = await _service.GetOneById(id);
            if (stock == null)
            {
                return NotFound();
            }

            return View(stock);
        }

        // GET: Stock/Create
        public IActionResult Create()
        {
            ViewData["ArticleID"] = new SelectList(_serviceArticle.QueryForStock().AsNoTracking(), "Id", "Libelle");
            return View();
        }

        // POST: Stock/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        /*
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ArticleID,Quantite")] StockEntity item)
        {
            if (ModelState.IsValid)
            {
                await _service.Add(item);
                return RedirectToAction(nameof(Index));
            }
            ViewData["ArticleID"] = new SelectList(_context.ArticleEntities, "Id", "Libelle", item.ArticleID);
            return View(item);
        }
        */

        // GET: Stock/Edit/5
        public async Task<IActionResult> Edit(int id)
        {

            var stock = await _service.GetOneById(id);
            if (stock == null)
            {
                return NotFound();
            }
            ViewData["ArticleID"] = new SelectList(_context.ArticleEntities, "Id", "Libelle", stock.ArticleID);
            return View(stock);
        }

        // POST: Stock/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ArticleID,Quantite")] StockEntity item)
        {
            if (id != item.ArticleID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _service.Update(item);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!Exists(item.ArticleID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ArticleID"] = new SelectList(_context.ArticleEntities, "Id", "Libelle", item.ArticleID);
            return View(item);
        }

        // GET: Stock/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            var stock = await _service.GetOneById(id);
            if (stock == null)
            {
                return NotFound();
            }

            return View(stock);
        }

        // POST: Stock/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _service.DeleteById(id);
            return RedirectToAction(nameof(Index));
        }

        private bool Exists(int id)
        {
            return _service.Exist(id);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AppStock</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AppStock</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    
                    <div class="dropdown">
                        <button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown">Contact
                        <span class="caret"></span></button>
                        <ul class="dropdown-menu">
                            <li><a class="nav-link text-dark" asp-area="" asp-controller="Contact" asp-action="Index">Coordonnées</a></li>
                        </ul>
                    </div> 
                    <div class="dropdown">
                        <button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown">Catalogue
                        <span class="caret"></span></button>
                        <ul class="dropdown-menu">
                            <li><a class="nav-link text-dark" asp-area="" asp-controller="Catalogue" asp-action="Index">Articles</a></li>
                            <li><a class="nav-link text-dark" asp-area="" asp-controller="Commande" asp-action="Panier">Panier</a></li>
                        </ul>
                    </div> 

                    <div class="dropdown">
                        <button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown">Administration
                        <span class="caret"></span></button>
                        <ul class="dropdown-menu">
                            <li><a class="nav-link text-dark" asp-area="" asp-controller="Fournisseur" asp-action="Index">Fournisseurs</a></li>
                            <li><a class="nav-link text-dark" asp-area="" asp-controller="Stock" asp-action="Index">Stocks</a></li>
                            <li><hr></li>
                            <li><a class="nav-link text-dark" asp-area="" asp-controller="Article" asp-action="Index">Articles</a></li>
                            <li><a class="nav-link text-dark" asp-area="" asp-controller="ArticleFamille" asp-action="Index">Familles</a></li>
                            <li><a class="nav-link text-dark" asp-area="" asp-controller="NomTypeTVA" asp-action="Index">TVA</a></li>
                            <li><hr></li>
                            <li><a class="nav-link text-dark" asp-area="" asp-controller="Inventaire" asp-action="Index">Inventaires</a></li>
                        </ul>
                    </div> 

                    <div class="dropdown">
                        <button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown">Commandes
                        <span class="caret"></span></button>
                        <ul class="dropdown-menu">
                            <li><a class="nav-link text-dark" asp-area="" asp-controller="Commande" asp-action="Index">Clients</a></li>
                            <li><a class="nav-link text-dark" asp-area="" asp-controller="CommandeFournisseur" asp-action="Index">Fournisseur</a></li>
                            <li><hr></li>
                            <li><a class="nav-link text-dark" asp-area="" asp-controller="Commande" asp-action="Dashboard">Traitement Clients</a></li>
                            <li><a class="nav-link text-dark" asp-area="" asp-controller="CommandeFournisseur" asp-action="Dashboard">Traitement Fournisseurs</a></li>
                            
                        </ul>
                    </div> 
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <!-- Modal -->
    <div id="testModal" class="modal fade" role="dialog">
        <div class="modal-dialog">

            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title"></h4>
                </div>
                <div class="modal-body">
                    <p>Some text in the modal.</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>

        </div>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - AppStock - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>